// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppSystems.Data;

#nullable disable

namespace WebAppSystems.Migrations
{
    [DbContext(typeof(WebAppSystemsContext))]
    [Migration("20250212005938_AjusteTablePedido")]
    partial class AjusteTablePedido
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAppSystems.Models.Attorney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attorney");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Avaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAvaria")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Avaria");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.FotoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoFotoVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("TipoPedido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("FotoPedido");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdicionalCarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdicionalDescarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteCargaId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteDescargaId")
                        .HasColumnType("int");

                    b.Property<int>("ColeteHomologado")
                        .HasColumnType("int");

                    b.Property<int>("CombustivelFinal")
                        .HasColumnType("int");

                    b.Property<int>("CombustivelInicial")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPretendida")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoSeguro")
                        .HasColumnType("int");

                    b.Property<int>("DocumentoVeiculo")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HoraFinal")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraPedido")
                        .HasColumnType("time");

                    b.Property<float>("KmFinal")
                        .HasColumnType("real");

                    b.Property<float>("KmInicial")
                        .HasColumnType("real");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoCarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoDescarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("TempoEsperaCarga")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TempoEsperaDescarga")
                        .HasColumnType("time");

                    b.Property<int>("TipoPedido")
                        .HasColumnType("int");

                    b.Property<int>("TrianguloHomologado")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCargaId");

                    b.HasIndex("ClienteDescargaId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Avaria", b =>
                {
                    b.HasOne("WebAppSystemsTransp.Models.Pedido", "Pedido")
                        .WithMany("Avarias")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.FotoPedido", b =>
                {
                    b.HasOne("WebAppSystemsTransp.Models.Pedido", "Pedido")
                        .WithMany("FotoPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Pedido", b =>
                {
                    b.HasOne("WebAppSystemsTransp.Models.Cliente", "ClienteCarga")
                        .WithMany("PedidosCarga")
                        .HasForeignKey("ClienteCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppSystemsTransp.Models.Cliente", "ClienteDescarga")
                        .WithMany("PedidosDescarga")
                        .HasForeignKey("ClienteDescargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppSystems.Models.Attorney", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId");

                    b.HasOne("WebAppSystemsTransp.Models.Veiculo", "Veiculo")
                        .WithMany("Pedidos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteCarga");

                    b.Navigation("ClienteDescarga");

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Cliente", b =>
                {
                    b.Navigation("PedidosCarga");

                    b.Navigation("PedidosDescarga");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Pedido", b =>
                {
                    b.Navigation("Avarias");

                    b.Navigation("FotoPedidos");
                });

            modelBuilder.Entity("WebAppSystemsTransp.Models.Veiculo", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
